VikMessage/VikMessage/apps/VikMessageApp/urls.py
from django.urls import path

from . import views

app_name = "VikMessage"

urlpatterns = [
    path("", views.main, name="main"),
    path("signUp/", views.signUp, name="signUp"),
    path("users/", views.index, name="index"),
    path("<int:user_id>/", views.detail, name="detail")
]

VikMessage/VikMessage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("VikMessageApp/", include("VikMessageApp.urls")),
    path('admin/', admin.site.urls),
]

VikMessage/VikMessage/apps/VikMessageApp/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    first_name = models.CharField("Имя", max_length=64)
    last_name = models.CharField("Фамилия", max_length=64)
    phone_number = models.CharField("Номер телефона", max_length=12, default="", unique=True)

    def __str__(self):
        return self.first_name + " " + self.last_name

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Message(models.Model):
    from_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    to_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    text = models.TextField("Текст сообщения")
    send_dateTime = models.DateTimeField(default=timezone.now, verbose_name='Дата и время отправки')
    edit_dateTime = models.DateTimeField(default=timezone.now, verbose_name='Дата и время редактирования')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

class Test(models.Model):
    field1 = models.IntegerField()
    field2 = models.CharField("field2", max_length=50)

    def __str__(self):
        return "field2 = " + self.field2

# class Chat(models.Model):
#     chat_Id = models.IntegerField(primary_key=True)
#     creator_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     name = models.CharField('Название чата', max_length=100)
#
#     def __str__(self):
#         return self.name + " id: " + self.id
#
#
# class Conversation(models.Model):
#     conversation_Id = models.IntegerField(primary_key=True)
#     creator_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     name = models.CharField('Название чата', max_length=100)
#
#     def __str__(self):
#         return self.name + " id: " + self.id
#
#
# class CommunicationAttendees(models.Model):
#     user_id = models.ForeignKey(User, on_delete=models.CASCADE)
#     chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
#     conversation_id = models.ForeignKey(Conversation, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return "It's a reference between attendees and communication"

VikMessage/VikMessage/apps/VikMessageApp/views.py
from django.shortcuts import render
from .models import User, Message
from django.http import Http404, HttpResponseRedirect


def main(request):
    return render(request, "VikMessage/main.html")


def signUp(request):
    try:
        user = User.objects.get(phone_number=request.POST['phone'])
    except:
        user = User()
    return render(request, "VikMessage/signUp.html")


def index(request):
    latest_users = User.objects.order_by("-first_name")[:5]
    return render(request, "VikMessage/list.html", {"latest_users": latest_users})


def detail(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except:
        raise Http404("User have not found!")
    return render(request, "VikMessage/detail.html", {"user": user})

VikMessage/VikMessage/templates/VikMessage/detail.html
{% extends "base.html" %}

{% block title %}{{user.first_name}} {{user.last_name}}{% endblock %}

{% block content %}



{% endblock %}

VikMessage/VikMessage/templates/VikMessage/list.html
{% extends "base.html" %}

{% block title %}Users{% endblock %}

{% block content %}

    {% if latest_users %}
        {% for user in latest_users %}
            <a href="{% url 'VikMessage:detail' user.id %}">{{user.first_name}} {{user.last_name}}</a>
        {% endfor %}
    {% else %}
        Users have not found
    {% endif %}
{% endblock %}

VikMessage/VikMessage/templates/VikMessage/main.html
{% extends "base.html" %}

{% block title %}Main Page{% endblock %}

{% block content %}

    <h2>Main page</h2>

{% endblock %}

VikMessage/VikMessage/templates/VikMessage/signUp.html
{% extends "base.html" %}

{% block title %}Main page{% endblock %}

{% block content %}

    <form class="form container form--invalid" action="{% url 'VikMessage:signUp' %}" method="post" autocomplete="off"> <!-- form
    --invalid -->
      <h2>Регистрация нового аккаунта</h2>
      <div class="form__item">
        <label for="name">Имя<sup>*</sup></label><br>
        <input id="name" type="text" name="name" placeholder="Введите имя">
      </div>
      <div class="form__item"> <!-- form__item--invalid -->
        <label for="phone">Номер телефона<sup>*</sup></label><br>
        <input id="phone" type="tel" name="phone" placeholder="+7хххххххххх" pattern="+7[0-9]{10}">
      </div>
      <div class="form__item">
        <label for="password">Пароль<sup>*</sup></label><br>
        <input id="password" type="password" name="password" placeholder="Введите пароль">
      </div>
      <br>
      <button type="submit" class="button">Зарегистрироваться</button><br><br>
      <a class="text-link" href="#">Уже есть аккаунт</a>
    </form>



{% endblock %}

VikMessage/VikMessage/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Месседжер{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>